### ISSUE TITLE
On problem in  04_00_Move.py

### ISSUE THREAD

**Issue by Landau0323** [ShoheiKobata/orin_bcap_python_samples#1]
In  04_00_Move.py, there is the following part:
```### TakeArm
Command = "TakeArm"
Param = [0,0]
m_bcapclient.robot_execute(HRobot,Command,Param)
print("TakeArm")
```

I believe that, the value for Param should be replaced with `Param = [0,1]`; otherwise, the robot gives an error and it does not move.

**Comment by ShoheiKobata** [comment]
Your interpretation is wrong. A command supported by RC8 specification b-CAP complies with RC8 Provider. For arguments of commands, refer to the following files.
`Param =[<ArmGroup> ， [<Keep>]] `
<Keep> is set 0 or 1.
0: Set the internal speed to 100, the current tool number to 0, and the current work number to 0.
1: Keep the current internal speed, the current tool number and the current work number without change. (0 by default)
If it was occurred error in your environment , please tell me error code displayed RC8(TP) or python.

**Comment by Landau0323** [comment]
Thank you for your explanation.
I tried TakeArm with the parameter you suggested, `[0,0]`, which causes the following error message in the terminal window:
```
Traceback (most recent call last):
  File "04_00_Move.py", line 40, in <module>
    m_bcapclient.robot_execute(HRobot,Command,Param)
  File "/home/arithmer/bcap/orin_bcap_python_samples-master/SimpleSamples/pybcapclient/bcapclient.py", line 314, in robot_execute
    return self._send_and_recv(64, [handle, command, param])[0]
  File "/home/arithmer/bcap/orin_bcap_python_samples-master/SimpleSamples/pybcapclient/bcapclient.py", line 548, in _send_and_recv
    raise ORiNException(hresult)
pybcapclient.orinexception.ORiNException: -2125459419
```
Can you see what kind of mistake I did?
I successfully ran the other sample codes which do not involve controlling arm, such as 02_00_IOReadWrite.py, so I believe that connecting with COBOTTA worked well.

My environment is the following:
OS: Ubuntu 16.04
Robot: COBOTTA
How to launch the robot: I launched the COBOTTA by using virtualTP with windows PC, then connect the Ubuntu PC above to the COBOTTA, and ran 04_00_Move.py .

Thank you so much for your effort.

**Comment by ShoheiKobata** [comment]
-2125459419 = 0xFFFF FFFF 8150 1025 
You can see it in RC8 error code tables.
Code 81501025 'This command is not available while an error occurs ' , 'This operation is not available when an error occurs. ' , 'Clear error and then retry. '
The error that occurred before 0x81501025 is the cause of the real error.

I have tested this program with COBOTTA.
