### ISSUE TITLE
Collision detection

### ISSUE THREAD

**Issue by Landau0323** [ShoheiKobata/orin_bcap_python_samples#2]
I want to use a function **"collision detection"** in controlling robot (VS068) with **bcaps in Python**, but I cound not find the way from manual.

- Is this function implemented in bCaps?
- If so, how can we use it (in Python)?

For the case that my statement is not clear enough, the following is lines of code when one uses collision detection function in pacscript:
```
Sub Main                                                       
 TakeArm keep = 1                   
 CollisionDetection True,1             
 Move P,J1                              
 CollisionDetection False,1               
 :
End Sub       
```

Thank you so much for using your time and effort.

**Comment by Landau0323** [comment]
I actually contacted customer support team at DENSOWAVE, and got an answer.
Using it, I wrote the following code, which solved my problem:

`m_bcapclient.robot_execute(HRobot, "CollisionDetection", [True, 1])`
to switch on collision detection function at Table 1.

Now I close this issue.

**Comment by Landau0323** [comment]
I was asked not to write about collision detection feature, as it is still not written in their manual.
Could you please delete this issue?

Thank you

**Comment by ShoheiKobata** [comment]
thank you for message .  It was nice to be able to resolve.
