### ISSUE TITLE
Define Tool 1, P(50, 0 0, 90, 0, 0)

### ISSUE THREAD

**Issue by mappold** [ShoheiKobata/orin_bcap_python_samples#20]
Dear Shohei Kobata,

do you know how to define a Tool using BCAP Python?

In PAC Script, the command is:
`Tool 1, P(5, 0, 0, 90, 0, 0)`

I tried to translate it to BCAP Python, but it doesn't work yet.

My guess is it should be something like:
`m_bcapclient.controller_execute(hCtrl, 'Tool', [1, [[50, 0, 0, 90, 0, 0], 'P']])`.

thank you.

Kind Regards,
Max

**Comment by ShoheiKobata** [comment]
@mappold 
The following is define a Tool using BCAP Python.
`m_bcapclient.robot_execute(hRobot, 'SetToolDef', [1, 'P(50, 0, 0, 90, 0, 0)'])`
A command reference can be found [here ](https://www.fa-manuals.denso-wave.com/subfolder/en/usermanuals/img/001511/RC8_ProvGuide_en.pdf).
5.2.29.59. CaoRobot::Execute("SetToolDef") command
Set the tool definition.
Syntax SetToolDef (<ToolNo>, <ToolDef>)
ToolNo : [in] Tool number (VT_I4)
ToolDef [in] Tool definition (P type Fig is ignored.)
X, Y, Z, RX, RY, RZ
Return value : None

**Comment by mappold** [comment]
Thanks a lot, it works!
