### ISSUE TITLE
Using bcap client with python2

### ISSUE THREAD

**Issue by frinklai** [ShoheiKobata/orin_bcap_python_samples#5]
HI, thanks for your example, it is very useful.
By the way, is that possible to run the example in [here ](https://github.com/ShoheiKobata/orin_bcap_python_samples/tree/master/SimpleSamples) with python2.7 ?

I notice there is a bcap py2 version, so may I just edit this line to `#!/usr/bin/env python` and import  [bcap py2 version](https://github.com/ShoheiKobata/orin_bcap_python_samples/blob/master/others/py2/bcapclient.py)?

Thank you very much for your reply. :)

**Comment by ShoheiKobata** [comment]
> By the way, is that possible to run the example in here with python2.7 ?
No. it is impossible with python2.7.

The library for py2 can be found [here](https://github.com/ShoheiKobata/orin_bcap_python_samples/tree/master/others/py2).
But I haven't been able to check it all.

**Comment by frinklai** [comment]
OK, I got it, thanks for your reply.
